/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author DAIYAN
 */
public class Groups extends javax.swing.JFrame {

    /**
     * Creates new form Groups
     */
    public Groups() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gA = new javax.swing.JButton();
        gB = new javax.swing.JButton();
        gC = new javax.swing.JButton();
        gD = new javax.swing.JButton();
        gH = new javax.swing.JButton();
        gG = new javax.swing.JButton();
        gF = new javax.swing.JButton();
        gE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(240, 0, 0));
        setForeground(java.awt.Color.red);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gA.setText("GROUP A");
        gA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gAActionPerformed(evt);
            }
        });
        getContentPane().add(gA, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 88, 134, 71));

        gB.setText("GROUP B");
        gB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBActionPerformed(evt);
            }
        });
        getContentPane().add(gB, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 209, 134, 71));

        gC.setText("GROUP C");
        gC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCActionPerformed(evt);
            }
        });
        getContentPane().add(gC, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 330, 134, 71));

        gD.setText("GROUP D");
        gD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDActionPerformed(evt);
            }
        });
        getContentPane().add(gD, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 451, 134, 71));

        gH.setText("GROUP H");
        gH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gHActionPerformed(evt);
            }
        });
        getContentPane().add(gH, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 451, 134, 71));

        gG.setText("GROUP G");
        gG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gGActionPerformed(evt);
            }
        });
        getContentPane().add(gG, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 330, 134, 71));

        gF.setText("GROUP F");
        gF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gFActionPerformed(evt);
            }
        });
        getContentPane().add(gF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 209, 134, 71));

        gE.setText("GROUP E");
        gE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEActionPerformed(evt);
            }
        });
        getContentPane().add(gE, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 88, 134, 71));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/back.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -10, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /*In the below functions,necessary actions performed to
    open each group by clicking on the group names*/
    
    private void gAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gAActionPerformed
         GroupA ga=new GroupA();
        ga.setVisible(true);
    }//GEN-LAST:event_gAActionPerformed

    private void gBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBActionPerformed
        GroupB gb = new GroupB();
        gb.setVisible(true); 
    }//GEN-LAST:event_gBActionPerformed

    private void gCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCActionPerformed
GroupC gb = new GroupC();
        gb.setVisible(true);
    }//GEN-LAST:event_gCActionPerformed

    private void gDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDActionPerformed
GroupD gb = new GroupD();
        gb.setVisible(true); 
    }//GEN-LAST:event_gDActionPerformed

    private void gEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEActionPerformed
GroupE gb = new GroupE();
        gb.setVisible(true);  
    }//GEN-LAST:event_gEActionPerformed

    private void gFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gFActionPerformed
GroupF gb = new GroupF();
        gb.setVisible(true);     
    }//GEN-LAST:event_gFActionPerformed

    private void gGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gGActionPerformed
GroupG gb = new GroupG();
        gb.setVisible(true);   
    }//GEN-LAST:event_gGActionPerformed

    private void gHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gHActionPerformed
GroupH gb = new GroupH();
        gb.setVisible(true);  
    }//GEN-LAST:event_gHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Groups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Groups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gA;
    private javax.swing.JButton gB;
    private javax.swing.JButton gC;
    private javax.swing.JButton gD;
    private javax.swing.JButton gE;
    private javax.swing.JButton gF;
    private javax.swing.JButton gG;
    private javax.swing.JButton gH;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
